algoritmo "Média das notas"
// Autor :    BABI
// Data : 07/04/2026
// Seção de Declarações 
var
    notaUm: real
    notaDois: real
    notaTres: real
    valorFinal: real
inicio
// comandos
   escreva ("informe a nota um")
   leia (notaUm)
   
   escreva ("informe a nota dois")
   leia (notaDois)
   
   escreva ("informe a nota três")
   leia (notaTres)
   
 // Agora iremos fazer a média!
 
 valorFinal<- notaUm + notaDois + notaTres/3
fimalgoritmo
