algoritmo "semnome"
// Função :
// Autor :
// Data : 13/04/2026
// Seção de Declarações 
var
   valorP: real
   valorAltura:real
   valorFinal: real

inicio
// Seção de Comandos

   escreva ("Digite seu peso")
   leia (valorP)
   escreva ("Digite sua altura em cm")
   leia (valorAltura)
   // Vamos calcular o IMC!!
   valorFinal<- valorP/ (valorAltura * valorAltura)

   escreval ("O valor de IMC referente ao seu peso foi", valorFinal)
fimalgoritmo
