algoritmo "Transformação de C° para F°"
// Autor :  babi
// Data : 13/04/2026
// Seção de Declarações 
var
      valorC: real
      valorFinal: real
inicio
// Seção de Comandos 
   escreva ("Escreva o valor da tempreratura")
   leia (valorC)

// Vamos realizar a transformação!!
   valorFinal<- (9 * valorC) / 5 +  32
   
   escreval ("A temperatura em C° convertida para F° foi", valorFinal)

fimalgoritmo
