algoritmo "Área do terreno"
// Autor :  babi
// Data : 13/04/2026
// Seção de Declarações 
var
   valorL: real
   valorC: real
   valorFinal: real

inicio
// Seção de Comandos 

   escreva ("Informe a metragem da largura do terreno")
   Leia (valorL)
   escreva ("Informe a metragem do comprimento do terreno")
   leia (valorC)

//Vamos calcular a área!

        valorFinal<- valorL * valorC
        
        escreval("A área do terreno é", valorFinal)
fimalgoritmo
