algoritmo "Soma"
// Autor : babi
// Data : 13/04/2026
// Seção de Declarações 
var
    valorUm: real
    valorDois: real
    valorFinal: real

inicio
// Comando
   escreva ("Informe um número")
   leia (valorUm)
   escreva ("Informe o segundo número")
   leia (valorDois)
   
   // Vamos calcular a soma!
   valorFinal<- valorUm + valorDois

   escreval ("A soma dos dois números foi", valorFinal)
   
fimalgoritmo
